name: myfirst-workflow
on: push
jobs:
   first_job:
         runs-on: ubuntu-latest
         steps: 
           - name: welcome message
             run: echo "myfirst new message"
           - name: List files
             run: ls
           - name: read file
             run: cat READ.me
