name: myfirst-workflow
on: push
jobs:
   first_job:
        runs_on: ubuntu-latest
        steps: 
          - name: welcome message
            run: echo "myfirst message"

          - name: List files
            run: ls
          - name: read file
            run: cat README.md
