name: Matrix strategy
on: 
    push:
    #workflow_dispatch:     
jobs:
   deploy:
      strategy:   
        matrix:             ##fail-fast ## max-parallel: 
          os: [ubuntu-latest,ubuntu-20.04,windows-latest]
          images: [hello-world,alpine]
          
      runs-on: ${{matrix.os}}
      steps: 
      - name: Echo Docker details
        run: docker info
      - name: Run images on ${{matrix.os}}
        run: docker run ${{matrix.images}}
      
   