name: exploring varibales and secrets
on: push
env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: ratnakaramphani@gmail.com
  IMAGE_NAME: github-actions-nginx
  DOCKER_PASSWORD: $h@r@N#2015
jobs:
   docker:
         runs-on: ubuntu-latest
         steps: 
         - name: Docker Build
           run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/$IMAGE_NAME:latest
         - name: Docker login
           run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
         - name: Docker Publish
           run: echo docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/$IMAGE_NAME:latest
   deploy:
      needs: docker
      runs-on: ubuntu-latest  
      steps:      
        - name: Docker run
          run: docker run -d -p 8080:80 ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/$IMAGE_NAME:latest
              
